print("adding website header")
print("adding website hero")
print("adding website about section")
print("update website font")
print("update website font")
print("update hero picture")
print("adding news section")
print("adding IT department")
print("adding training department")
print("adding workshops department")
print("adding HR department")
